### ISSUE TITLE
Client Boostrap Theme

### ISSUE THREAD

**Issue by awwong1** [udia-software/udia#15]
Write a client bootstrap theme instead of using basic Bootstrap.

Inspiration:
* [Semantic UI](http://semantic-ui.com/usage/layout.html)
* [Creative Tim](http://www.creative-tim.com/)

**Comment by awwong1** [comment]
@askalburgi eh

**Comment by askalburgi** [comment]
Hey did you still want me to do this? I'm pretty busy figuring life out post-hackathon, but I can still try to make time to take a look :)

**Comment by awwong1** [comment]
No it's alright. I moved it to closed because I am using another UI
framework instead of bootstrap 😃
