### ISSUE TITLE
Not sure if bug or inconsistency is on purpose 😃 with the user names

### ISSUE THREAD

**Issue by nettapper** [udia-software/udia#67]
I just stopped by to check in and see how things are going on [the public site](https://a.udia.ca). When I noticed that although all three 'udia' users appear to be links the top level on is in a black-colored font while the others are in the blue-colored font. [Found in this thread](https://a.udia.ca/posts/11-be-careful-what-you-wish-for-) 

![image](https://cloud.githubusercontent.com/assets/1553392/25293934/2e838c40-269a-11e7-88a3-d482429e5ba4.png)

Also seems to be happening in [other threads](https://a.udia.ca/posts/8-belp)

![image](https://cloud.githubusercontent.com/assets/1553392/25294003/8209228a-269a-11e7-807b-0dfb6bbf9149.png)

Granted, this could be due to older posts being mixed in, different versions, or fixed in you local dev version. Hope things are well 😄

**Comment by awwong1** [comment]
Definitely a bug! Currently working on this in the React version of the application @nettapper

**Comment by awwong1** [comment]
Issue is marked as wont fix as addressed in rewrite
